name: Deploy to Server

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install -f
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2
        with:
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
          REMOTE_PORT: ${{ secrets.SERVER_PORT }}
          SOURCE: "."  # Use "." to deploy all files in the current directory
          TARGET: "/home/armconstructions.in/public_html/vishmatebackend"
          ARGS: "-rltgoDzvO --delete"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
